CREATE TABLE Task (
    id BIGINT(20) NOT NULL AUTO_INCREMENT,
    statement VARCHAR(255) NOT NULL,
    task_order INT NOT NULL,
    course_id BIGINT(20) NOT NULL,
    task_type VARCHAR(50) NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT FK_Task_Course FOREIGN KEY (course_id) REFERENCES Course(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `Option` (
    id BIGINT(20) NOT NULL AUTO_INCREMENT,
    text VARCHAR(80) NOT NULL,
    is_correct BOOLEAN NOT NULL,
    task_id BIGINT(20) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT FK_Option_Task FOREIGN KEY (task_id) REFERENCES Task(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;